name: Backend pytests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checout repository code
        uses: actions/checkout@v2

      - name: Initialize Python 2.7
        uses: actions/setup-python@v2
        with:
            python-version: 2.7    
      - run: pip install -r requirements.txt
        working-directory: ./backend
      - run: pytest test_backend.py
        working-directory: ./backend
