name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Python 2.7
        uses: actions/setup-python@v1
        with:
            python-version: 2.7
      - run: pip install -r requirements.txt
        working-directory: ./backend
      - run: pytest test_backend.py
        working-directory: ./backend
